server:
  port: 9006

spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.163.134
      database: spitdb
  redis:
    host: 192.168.163.134

eureka:
  #客户端注册进eureka服务列表内
  client:
    service-url:
      #单机版
      defaultZone: http://tensquare-eureka6868.com:6868/eureka/
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #自定义服务名称信息
    instance-id: tensquare-spit9006
    #访问路径可以显示IP地址
    prefer-ip-address: true

info:
  app.name: tensquare
  company.name: www.tensquare.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
