server:
  port: 9008

spring:
  application:
    name: tensquare-user
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.163.134:3306/tensquare_user?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  jpa:
      database: mysql
      show-sql: true
      generate-ddl: true
  redis:
    host: 192.168.163.134
  rabbitmq:
    host: 192.168.163.134
jwt:
  config:
    key: zzb8391cjzzb
#   一个小时过期
    ttl: 3600000

eureka:
  #客户端注册进eureka服务列表内
  client:
    service-url:
      #单机版
      defaultZone: http://tensquare-eureka6868.com:6868/eureka/
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #自定义服务名称信息
    instance-id: tensquare-user9008
    #访问路径可以显示IP地址
    prefer-ip-address: true

info:
  app.name: tensquare
  company.name: www.tensquare.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
