#ServerProperties
server:
  port: 9012

spring:
  #微服务对外暴露的服务名
  application:
    name: tensquare-web

zuul:
  #ignored-services: "*" 禁止 网关+原服务名 进行访问
    #禁止 网关+原服务名 这样的请求路径进行访问微服务
    #比如问答服务 http://localhost:9012/tensquare-qa/problem/label/1 会报错

    #只能通过 网关+路径映射 进行访问微服务
    #比如问答服务 http://localhost:9012/qa/problem/label/1

    #或者不通过网关，直接访问微服务
    #比如问答服务 http://localhost:9003/problem/label/1
  ignored-services: "*"
  routes:
    tensquare-gathering: #活动
      path: /gathering/** #配置请求URL的请求规则
      serviceId: tensquare-gathering #指定Eureka注册中心中的服务id
    tensquare-article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: tensquare-article #指定Eureka注册中心中的服务id
    tensquare-base: #基础
      path: /base/** #配置请求URL的请求规则
      serviceId: tensquare-base #指定Eureka注册中心中的服务id
    tensquare-friend: #交友
      path: /friend/** #配置请求URL的请求规则
      serviceId: tensquare-friend #指定Eureka注册中心中的服务id
    tensquare-qa: #问答
      path: /qa/** #配置请求URL的请求规则
      serviceId: tensquare-qa #指定Eureka注册中心中的服务id
    tensquare-recruit: #招聘
      path: /recruit/** #配置请求URL的请求规则
      serviceId: tensquare-recruit #指定Eureka注册中心中的服务id         
    tensquare-spit: #吐槽
      path: /spit/** #配置请求URL的请求规则
      serviceId: tensquare-spit #指定Eureka注册中心中的服务id     
    tensquare-user: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: tensquare-user #指定Eureka注册中心中的服务id
    tensquare-search: #搜索
      path: /search/** #配置请求URL的请求规则
      serviceId: tensquare-search #指定Eureka注册中心中的服务id
    tensquare-sms: #手机验证码
      path: /sms/** #配置请求URL的请求规则
      serviceId: tensquare-sms #指定Eureka注册中心中的服务id

eureka:
  #客户端注册进eureka服务列表内
  client:
    service-url:
      defaultZone: http://tensquare-eureka6868.com:6868/eureka/
  instance:
    #自定义服务名称信息
    instance-id: tensquare-manager9012
    #访问路径可以显示IP地址
    prefer-ip-address: true

info:
  app.name: tensquare
  company.name: www.tensquare.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
